version: '3.7'

services:
  database:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: gameapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      

volumes:  # Corrected from "valumes" to "volumes"
  dbdata:
